export const  IMAGES  = [
  {
    id: 1,
    src: "./gallery/Work/work-1/Эля_1.jpg",
    alt: "Эля.jpg",
    images: [
      { src: "./gallery/Work/work-1/Эля_1.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-1/Эля_2.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-1/Эля_3.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-1/Эля_4.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-1/Эля_5.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-1/Эля_6.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-1/Эля_7.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-1/Эля_8.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-1/Эля_9.jpg", alt: "test-1.jpg" },
    ],
  },
  {
    id: 2,
    src: "./gallery/Work/work-2/Dasha_1.jpg",
    alt: "gallery-2.jpg",
    images: [
      { src: "./gallery/Work/work-2/Dasha_1.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-2/Dasha_2.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_3.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_4.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_5.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_6.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_7.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_8.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_9.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_10.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_11.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_12.jpg", alt: "test-1.jpg" },
      { src: "./gallery/Work/work-2/Dasha_13.jpg", alt: "test-1.jpg" },
    ],
  },
  {
    id: 3,
    src: "./gallery/Work/work-3/Dopey_1.jpg",
    alt: "gallery-2.jpg",
    images: [
      { src: "./gallery/Work/work-3/Dopey_1.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_2.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_3.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_4.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_5.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_6.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_7.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_8.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_9.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_10.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_11.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_12.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_13.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-3/Dopey_14.jpg", alt: "Эля.jpg" },
    ],
  },
  {
    id: 4,
    src: "./gallery/Work/work-4/Vasina_1.jpg",
    alt: "Эля.jpg",
    images: [
      { src: "./gallery/Work/work-4/Vasina_1.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-4/Vasina_2.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-4/Vasina_3.jpg", alt: "Эля.jpg" },
      { src: "./gallery/Work/work-4/Vasina_4.jpg", alt: "Эля.jpg" },
    ],
  },
];
